### ISSUE TITLE
Is looping supported?

### ISSUE THREAD

**Issue by sietsevanderbom** [Mickael-Roger/chaostoolkit-ansible#15]
I tried something like:
```
      ansible:
        module: shell
        args:
          cmd: "{{ item }}"
        loop:
          - 'touch test'
          - 'sleep 10'
          - 'touch test2.txt'
 ```

But get: `The error was: 'item' is undefined. 'item' is undefined"`
